import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

import Header from '../components/Header'
import Showcase from '../components/Showcase'
import Products from '../components/Products'
import Contact from '../components/Contact'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        {/* <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/> */}
        <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300;400;600;700&display=swap" rel="stylesheet"/>

      </Head>
     <main className='flex flex-col md:overflow-x-hidden'>
        <Header/>
        <Showcase/>
        <Products/>
        <Contact/>
     </main>
    </>
  )
}
